server:
  port: 8081

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8071/eureka/

spring:
  application:
    name: eureka-server