server:
  port: 8084

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/

spring:
  application:
    name: eureka-consumer